baseURL = 'https://sebster3.github.io/betty/'
languageCode = 'en-us'
theme = 'hyde'

# Website title
title = 'Betty Mendez'

# Google Analytics
# googleAnalytics = "tracking code"

# Sidebar menu items
[Menus]
    main = [
        {Name = "Home", URL = "/", Weight = 1},
        {Name = "About", URL = "/about", Weight = 2},
        {Name = "Contact", URL = "/contact", Weight = 3}
    ]

[params]
    description = "Crafting your cherished memories for over a decade"
    themeColor = "theme-betty"

[taxonomies]
    tag = "tags"
    category = "categories"
    kind = "kinds"
